FROM node:10-alpine

RUN apt-get update && apt-get install -y --no-install-recommends \
  python3.5 \
  python3-pip \
  build-essential \
  make \
  && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app/

COPY package*.json ./

RUN npm install --production

COPY app.js ./

EXPOSE 9229

USER node

CMD ["node", "--inspect=0.0.0.0:9229", "app.js"]
